name: Run Tests

on:
  push:
    branches:
      - main # Adjust to match the branch you want to monitor
  pull_request:
    branches:
      - main # Adjust for PRs into your target branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:6.5-management
        ports:
          - 5672:5672
          - 15672:15672
        options: > 
          --health-cmd="curl --silent --fail localhost:15672/ > /dev/null"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Run tests
      - name: Run Tests
        run: dotnet test --no-build --configuration Release
